name: p workflow
on: workflow_dispatch
jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Print goodbye
        run: echo "Done - Bye" 
